### ISSUE TITLE
Forum software loses logins/fails to log in

### ISSUE THREAD

**Issue by gcp** [mozilla/node-janus#20] opened 2014-07-11 12:03 UTC
Observed on several PHP-based forums, including vBulletin based and IPB based.
1. Try to load hydrogenaud.io
2. Observe very slow load
3. Observe the site layout breaks (at least it did here sometimes, may be timing out)
4. Try to log in (need to create an account)
5. Logging in always fails, you are always directed back to the front page.

**Comment by eamsen** [comment] 2014-07-11 12:31
Confirmed for http://www.hydrogenaud.io/forums.
The issue is connected with setting `proxy.followRedirects` and is only reproducing when set to `true`.

**Comment by eamsen** [comment] 2014-07-15 13:15
Fixed by disabling redirects resolution, but we should investigate a way to enable it without breaking the web.

**Comment by Ackar** [comment] 2014-07-16 06:23
The problem comes from cookies. The page send a 302 response with a session cookie, then the follow-redirects plugin follow the redirection and discard the cookie. So the client only get a 200 response without the session cookie.

So, we could either not follow redirections when the 'set-cookie' header exists, or aggregate cookies (while we remain on the same domain) and send them with the final response. I'm not sure of what's the best solution here...

**Comment by eamsen** [comment] 2014-07-16 14:24
@Ackar I think every response that effects the client besides triggering a redirect should be forwarded to the client. So I would prefer not to add complexity by aggregating cookies and just not follow the redirect in such a case.

Besides this, @gcp has also reported that the follow-redirect feature asked for unknown resources, so there might be another issue with a mangled request path.

**Comment by eamsen** [comment] 2014-11-12 00:30
followRedirects has been dead for long time, closing.

**Closed as completed by eamsen** 2014-11-12 00:30 UTC
Labels: bug
